name:                RosenDiscreteMath
version:             0.1.0.0
github:              "vincenteof/RosenDiscreteMath"
license:             BSD3
author:              "vincenteof"
maintainer:          "vincenteof@qq.com"
copyright:           "GPL"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vincenteof/RosenDiscreteMath#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  RosenDiscreteMath-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RosenDiscreteMath

tests:
  RosenDiscreteMath-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RosenDiscreteMath
